Update dbt-testing.yml

diff --git a/.github/workflows/dbt-testing.yml b/.github/workflows/dbt-testing.yml
--- a/.github/workflows/dbt-testing.yml
+++ b/.github/workflows/dbt-testing.yml
@@ -24,21 +24,27 @@ on:
         description: 'This is just a Dummy Input for Manual Runs'
         required: false
         type: string
+      branch:
+        description: |
+          The branch to check out for running DBT tests. 
+          By default, this checks out the code from the branch where the workflow was triggered.
+        required: false
+        type: string
+        default: ${{ github.ref_name }}
 
   # TODO: Once we are happy with the manual runs, we will need to define the github
   # or git actions that will trigger this Github Action .
 
   #Workflows will not run on pull_request activity if the pull request has a merge conflict.
   #By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
-  pull_request:
-    types:
-      - opened
-      - synchronize
-      - reopened
-      - labeled
-      - ready_for_review
-    branches:
-      - main
+#  pull_request:
+#    types:
+#      - opened
+#      - synchronize
+#    branches:
+#      - main
+#    paths:
+#     - 'dp_airflow/dbt/**'
 
 # TODO: Should we have concurrency setting to control how many actions can run in parallel?
 
@@ -53,6 +59,13 @@ jobs:
     # https://github.com/actions/runner-images/blob/ubuntu22/20240804.1/images/ubuntu/Ubuntu2204-Readme.md
     runs-on: ubuntu-latest
 
+    #Specify location of the profiles.yml configuration file and project directory
+    #And name of the secret containing the token to connect to Databricks
+    env:
+      DBT_PROFILES_DIR: ./dp_airflow/dbt/data_platform
+      DBT_PROJECT_DIR: ./dp_airflow/dbt/data_platform
+      DATABRICKS_TOKEN_RED: ${{ secrets.databricks_token_red }}
+
     # Each job has Steps - each step has its own process in the runner, so variables are not shared. See:
     # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
     steps:
@@ -60,12 +73,33 @@ jobs:
         run: |
           echo This is the skeleton of the CICD Task. Our Input is: ${{inputs.example}}
 
-    # TODO: Lets have a step which installs DBT
-
     # TODO: Lets have a step to checkout the code in the branch we want to update.
     #  (how do we do this with manual input?)
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || inputs.branch }}
 
-    # TODO: Can we use that code to connect to Databricks?
+    # TODO: Lets have a step which installs DBT
+      - name: Choose python version
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
+
+      - name: Install dbt and databricks adapter
+        run: |
+          python -m pip install dbt-core dbt-databricks
+
+      - name: Verify dbt installation
+        run: |
+          dbt --version
+          dbt deps --target predeployment --profiles-dir "$DBT_PROFILES_DIR" --project-dir "$DBT_PROJECT_DIR"
+
+    # # TODO: Can we use that code to connect to Databricks?
+    # DBT handles connections to Databricks using the credentials provided in the profiles.yml file
+      - name: Check databricks connection
+        run: |
+          dbt debug --target predeployment --profiles-dir "$DBT_PROFILES_DIR" --project-dir "$DBT_PROJECT_DIR"
 
     # TODO: How can we detect which models have changed?
 
@@ -78,3 +112,8 @@ jobs:
     # TODO: How can we clean up the cloned tables we have created?
 
     # TODO: How can we fail the github action if the tests fail?
+      - name: Fail Action on Test Failure
+        if: failure()
+        run: |
+          echo "Tests have failed"
+          exit 1
