Update dbt-testing.yml

diff --git a/.github/workflows/dbt-testing.yml b/.github/workflows/dbt-testing.yml
--- a/.github/workflows/dbt-testing.yml
+++ b/.github/workflows/dbt-testing.yml
@@ -37,14 +37,14 @@ on:
 
   #Workflows will not run on pull_request activity if the pull request has a merge conflict.
   #By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
-#  pull_request:
-#    types:
-#      - opened
-#      - synchronize
-#    branches:
-#      - main
-#    paths:
-#     - 'dp_airflow/dbt/**'
+  pull_request:
+    types:
+    - opened
+    -  synchronize
+    branches:
+    - main
+    paths:
+    - 'dp_airflow/dbt/**'
 
 # TODO: Should we have concurrency setting to control how many actions can run in parallel?
 
@@ -78,7 +78,7 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || inputs.branch }}
+          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || inputs.branch }}
 
     # TODO: Lets have a step which installs DBT
       - name: Choose python version
@@ -90,16 +90,16 @@ jobs:
         run: |
           python -m pip install dbt-core dbt-databricks
 
-      - name: Verify dbt installation
-        run: |
-          dbt --version
-          dbt deps --target predeployment --profiles-dir "$DBT_PROFILES_DIR" --project-dir "$DBT_PROJECT_DIR"
+    #   - name: Verify dbt installation
+    #     run: |
+    #       dbt --version
+    #       dbt deps --target predeployment --profiles-dir "$DBT_PROFILES_DIR" --project-dir "$DBT_PROJECT_DIR"
 
     # # TODO: Can we use that code to connect to Databricks?
-    # DBT handles connections to Databricks using the credentials provided in the profiles.yml file
-      - name: Check databricks connection
-        run: |
-          dbt debug --target predeployment --profiles-dir "$DBT_PROFILES_DIR" --project-dir "$DBT_PROJECT_DIR"
+    # # DBT handles connections to Databricks using the credentials provided in the profiles.yml file
+    #   - name: Check databricks connection
+    #     run: |
+    #       dbt debug --target predeployment --profiles-dir "$DBT_PROFILES_DIR" --project-dir "$DBT_PROJECT_DIR"
 
     # TODO: How can we detect which models have changed?
 
@@ -112,8 +112,8 @@ jobs:
     # TODO: How can we clean up the cloned tables we have created?
 
     # TODO: How can we fail the github action if the tests fail?
-      - name: Fail Action on Test Failure
-        if: failure()
-        run: |
-          echo "Tests have failed"
-          exit 1
+      # - name: Fail Action on Test Failure
+      #   if: failure()
+      #   run: |
+      #     echo "Tests have failed"
+      #     exit 1
